import { callLLM, type LLMConfig } from '../llm.js'
import { resolve } from 'path'
import { mkdir } from 'fs/promises'
import { buildContext, type ContextResult } from '../context.js'
import { readArchitecture, writeArchitecture } from '../memory.js'

/**
 * Formats a ContextResult into a prompt-ready string for the planner.
 *
 * @param ctx - The context result from buildContext
 * @returns Formatted context string
 */
function formatContextForPrompt(ctx: ContextResult): string {
  const parts: string[] = []
  parts.push('## Project File Tree')
  parts.push(ctx.fileTree)

  if (ctx.chunks.length > 0) {
    parts.push('\n## Relevant Code')
    for (const chunk of ctx.chunks) {
      parts.push(`\n### ${chunk.filePath} (L${chunk.startLine}-${chunk.endLine})`)
      parts.push(`\`\`\`\n${chunk.content}\n\`\`\``)
    }
  }

  return parts.join('\n')
}

/**
 * A question generated by the planner for the user.
 */
export interface Question {
  id: number
  question: string
}

/**
 * An answer provided by the user to a planner question.
 */
export interface Answer {
  id: number
  answer: string
}

/**
 * Supported agent types for task execution.
 */
export type AgentType = 'code' | 'debug' | 'test' | 'refactor'

/**
 * Status of a task in the execution pipeline.
 */
export type TaskStatus = 'pending' | 'running' | 'done' | 'failed' | 'escalated'

/**
 * A single atomic task in an execution plan.
 */
export interface Task {
  id: string
  description: string
  dependencies: string[]
  filesLikelyAffected: string[]
  agentType: AgentType
  status: TaskStatus
}

/**
 * A complete execution plan generated by the planner.
 */
export interface Plan {
  id: string
  intent: string
  tasks: Task[]
  raw: string
  createdAt: number
}

/** System prompt for the question generation call. */
const QUESTION_SYSTEM_PROMPT = `You are a senior developer analyzing a codebase before starting work.
Identify exactly what is ambiguous in the user's request.
Ask 3-6 focused, specific questions.
Do NOT ask things already answerable from the codebase.
Respond ONLY in JSON: { "questions": [{ "id": number, "question": string }] }`

/** System prompt for the plan generation call. */
const PLAN_SYSTEM_PROMPT = `You are a senior developer creating an execution plan.
Generate a precise markdown checklist of tasks to complete.
Each item must be one atomic task for one agent.
Tasks that can run in parallel must have no shared files.

For each task item, use this exact format:
- [ ] [TASK_ID:t1] [TYPE:code] [DEPS:none] [FILES:src/file1.ts,src/file2.ts] Description of the task

Where:
- TASK_ID is a unique short id (t1, t2, t3...)
- TYPE is one of: code, debug, test, refactor
- DEPS is comma-separated list of task IDs this depends on, or "none"
- FILES is comma-separated list of files that may be affected

Respond with markdown only. No JSON. No explanations outside the checklist.`

/**
 * Generates a unique plan ID.
 *
 * @returns A unique string identifier for the plan
 */
function generatePlanId(): string {
  const timestamp = Date.now().toString(36)
  const random = Math.random().toString(36).substring(2, 8)
  return `plan-${timestamp}-${random}`
}

/**
 * Ensures the plan storage directory exists.
 *
 * @param projectRoot - Absolute project root path
 * @param planId - Plan identifier
 * @returns Absolute path to the plan directory
 */
async function ensurePlanDir(projectRoot: string, planId: string): Promise<string> {
  const planDir = resolve(projectRoot, '.drex', 'plans', planId)
  await mkdir(planDir, { recursive: true })
  return planDir
}

/**
 * Call 1 — Generates clarifying questions based on user intent and codebase.
 *
 * @param projectRoot - Absolute project root path
 * @param intent - User's stated intent/goal
 * @param apiKey - Anthropic API key
 * @param model - LLM model identifier
 * @returns Object with planId and generated questions
 */
export async function generateQuestions(
  projectRoot: string,
  intent: string,
  config: LLMConfig
): Promise<{ planId: string; questions: Question[] }> {
  const planId = generatePlanId()
  const planDir = await ensurePlanDir(projectRoot, planId)

  const contextResult = await buildContext(projectRoot, { description: intent, filesLikelyAffected: [] })
  const contextContent = formatContextForPrompt(contextResult)
  const architecture = await readArchitecture(projectRoot)

  const userPrompt = [
    `## User Intent\n${intent}`,
    architecture ? `\n## Current Architecture\n${architecture}` : '',
    `\n## Codebase\n${contextContent}`,
  ].join('\n')

  const responseText = await callLLM(
    config,
    [{ role: 'user', content: userPrompt }],
    QUESTION_SYSTEM_PROMPT
  )

  let parsed: unknown
  try {
    parsed = JSON.parse(responseText.trim())
  } catch {
    /* Try extracting JSON from code fences */
    const fenceMatch = /```(?:json)?\s*\n?([\s\S]*?)\n?\s*```/.exec(responseText)
    if (fenceMatch?.[1]) {
      parsed = JSON.parse(fenceMatch[1].trim())
    } else {
      throw new Error('Failed to parse questions JSON from LLM response')
    }
  }

  const questionsData = parsed as { questions: Question[] }
  if (!questionsData.questions || !Array.isArray(questionsData.questions)) {
    throw new Error('LLM response missing "questions" array')
  }

  const questions: Question[] = questionsData.questions.map((questionItem, index) => ({
    id: questionItem.id ?? index + 1,
    question: questionItem.question,
  }))

  /* Save questions to plan directory */
  await Bun.write(
    resolve(planDir, 'questions.json'),
    JSON.stringify(questions, null, 2)
  )

  return { planId, questions }
}

/**
 * Parses a markdown task checklist into structured Task objects.
 * Extracts metadata from the [TASK_ID:...] [TYPE:...] [DEPS:...] [FILES:...] format.
 *
 * @param markdown - Raw markdown from the LLM
 * @returns Array of parsed Task objects
 */
function parseMarkdownTasks(markdown: string): Task[] {
  const tasks: Task[] = []
  const taskPattern = /- \[ \]\s*\[TASK_ID:(\w+)\]\s*\[TYPE:(\w+)\]\s*\[DEPS:([^\]]*)\]\s*\[FILES:([^\]]*)\]\s*(.*)/g

  let match: RegExpExecArray | null
  while ((match = taskPattern.exec(markdown)) !== null) {
    const taskId = match[1] ?? `t${tasks.length + 1}`
    const typeStr = match[2] ?? 'code'
    const depsStr = match[3] ?? 'none'
    const filesStr = match[4] ?? ''
    const description = match[5]?.trim() ?? ''

    const validTypes: AgentType[] = ['code', 'debug', 'test', 'refactor']
    const agentType: AgentType = validTypes.includes(typeStr as AgentType)
      ? (typeStr as AgentType)
      : 'code'

    const dependencies = depsStr === 'none' || depsStr === ''
      ? []
      : depsStr.split(',').map((dep) => dep.trim())

    const filesLikelyAffected = filesStr === '' || filesStr === 'none'
      ? []
      : filesStr.split(',').map((file) => file.trim())

    tasks.push({
      id: taskId,
      description,
      dependencies,
      filesLikelyAffected,
      agentType,
      status: 'pending',
    })
  }

  /* Fallback: parse simple markdown checklist if structured format fails */
  if (tasks.length === 0) {
    const simplePattern = /- \[ \]\s+(.*)/g
    let simpleMatch: RegExpExecArray | null
    let index = 1

    while ((simpleMatch = simplePattern.exec(markdown)) !== null) {
      const description = simpleMatch[1]?.trim() ?? ''
      tasks.push({
        id: `t${index}`,
        description,
        dependencies: index > 1 ? [`t${index - 1}`] : [],
        filesLikelyAffected: [],
        agentType: 'code',
        status: 'pending',
      })
      index++
    }
  }

  return tasks
}

/**
 * Call 2 — Generates an execution plan after receiving user answers to questions.
 *
 * @param projectRoot - Absolute project root path
 * @param planId - Plan identifier from the question phase
 * @param intent - User's original intent
 * @param answers - User's answers to the generated questions
 * @param apiKey - Anthropic API key
 * @param model - LLM model identifier
 * @returns Complete Plan object with parsed tasks
 */
export async function generatePlan(
  projectRoot: string,
  planId: string,
  intent: string,
  answers: Answer[],
  config: LLMConfig
): Promise<Plan> {
  const planDir = await ensurePlanDir(projectRoot, planId)

  const contextResult = await buildContext(projectRoot, { description: intent, filesLikelyAffected: [] })
  const contextContent = formatContextForPrompt(contextResult)
  const architecture = await readArchitecture(projectRoot)

  /* Load original questions */
  let questionsText = ''
  try {
    const questionsFile = Bun.file(resolve(planDir, 'questions.json'))
    const exists = await questionsFile.exists()
    if (exists) {
      const questions = JSON.parse(await questionsFile.text()) as Question[]
      questionsText = questions.map((questionItem) => `Q${questionItem.id}: ${questionItem.question}`).join('\n')
    }
  } catch {
    /* proceed without questions context */
  }

  const answersText = answers.map((answerItem) => `A${answerItem.id}: ${answerItem.answer}`).join('\n')

  const userPrompt = [
    `## User Intent\n${intent}`,
    architecture ? `\n## Current Architecture\n${architecture}` : '',
    questionsText ? `\n## Questions Asked\n${questionsText}` : '',
    `\n## User Answers\n${answersText}`,
    `\n## Codebase\n${contextContent}`,
  ].join('\n')

  const rawMarkdown = await callLLM(
    config,
    [{ role: 'user', content: userPrompt }],
    PLAN_SYSTEM_PROMPT
  )

  /* Save raw plan markdown */
  await Bun.write(resolve(planDir, 'plan.md'), rawMarkdown)

  /* Parse tasks from markdown */
  const tasks = parseMarkdownTasks(rawMarkdown)

  if (tasks.length === 0) {
    throw new Error('Plan generation produced zero tasks. LLM output may be malformed.')
  }

  /* Update architecture summary */
  await writeArchitecture(projectRoot, `# Architecture Summary\nUpdated after plan: ${planId}\nIntent: ${intent}\n\nTasks: ${tasks.length}`)

  const plan: Plan = {
    id: planId,
    intent,
    tasks,
    raw: rawMarkdown,
    createdAt: Date.now(),
  }

  /* Save structured plan */
  await Bun.write(resolve(planDir, 'plan.json'), JSON.stringify(plan, null, 2))

  return plan
}
