/**
 * Shared TypeScript types for the DREX desktop application.
 * These mirror types from drex-core and add app-specific types.
 */

// ─── Core types mirrored from drex-core ────────────────────────────────────

/** Supported agent types for task execution. */
export type AgentType = 'code' | 'debug' | 'test' | 'refactor'

/** Status of a task in the execution pipeline. */
export type TaskStatus = 'pending' | 'running' | 'done' | 'failed' | 'escalated'

/** States of the orchestrator state machine. */
export type OrchestratorState =
  | 'IDLE'
  | 'PLANNING'
  | 'AWAITING_ANSWERS'
  | 'AWAITING_APPROVAL'
  | 'EXECUTING'
  | 'DONE'
  | 'FAILED'

/** A question generated by the planner for the user. */
export interface Question {
  id: number
  question: string
}

/** An answer provided by the user to a planner question. */
export interface Answer {
  id: number
  answer: string
}

/** A single atomic task in an execution plan. */
export interface Task {
  id: string
  description: string
  dependencies: string[]
  filesLikelyAffected: string[]
  agentType: AgentType
  status: TaskStatus
  reviewerFeedback?: string
  retryCount?: number
  rawOutput?: string
  actionsExecuted?: ActionRecord[]
}

/** Record of an action executed by an agent. */
export interface ActionRecord {
  type: 'edit_file' | 'create_file' | 'delete_file' | 'run_command'
  path?: string
  command?: string
  timestamp: number
}

/** A complete execution plan generated by the planner. */
export interface Plan {
  id: string
  intent: string
  tasks: Task[]
  raw: string
  createdAt: number
}

/** Summary of a completed plan execution. */
export interface Summary {
  planId: string
  tasksTotal: number
  tasksDone: number
  tasksFailed: number
  tasksEscalated: number
  durationMs: number
}

// ─── Provider / Model types ─────────────────────────────────────────────────

/** A model available in a provider. */
export interface ModelInfo {
  name: string
  contextWindow?: number
}

/** An LLM provider configuration. */
export interface Provider {
  id: string
  name: string
  baseURL: string
  logo: string
  models: string[]
  apiKey?: string
  isDefault: boolean
  isActive: boolean
}

// ─── Project types ──────────────────────────────────────────────────────────

/** A recently opened project. */
export interface RecentProject {
  path: string
  name: string
  lastUsed: number
  taskCount?: number
}

// ─── Session / Log types ────────────────────────────────────────────────────

/** Type of a log entry in the session log stream. */
export type LogType =
  | 'task:start'
  | 'task:done'
  | 'review:fail'
  | 'command'
  | 'error'
  | 'info'
  | 'plan:questions'
  | 'plan:ready'

/** A single log entry in the session stream. */
export interface LogEntry {
  id: string
  timestamp: number
  type: LogType
  message: string
  taskId?: string
}

// ─── Config types ────────────────────────────────────────────────────────────

/** Permission level for agent actions. */
export type PermissionLevel = 'safe' | 'moderate' | 'full'

/** Application-wide configuration stored in config.json. */
export interface AppConfig {
  providers: Provider[]
  activeProvider: string
  activeModel: string
  maxConcurrentAgents: number
  permissionLevel: PermissionLevel
  recentProjects: RecentProject[]
  autoApprovePlans: boolean
}

// ─── RPC event types ─────────────────────────────────────────────────────────

/** A drex:event payload sent from main to renderer. */
export type DrexEvent =
  | { type: 'plan:questions'; payload: { planId: string; questions: Question[] } }
  | { type: 'plan:ready'; payload: Plan }
  | { type: 'task:start'; payload: Task }
  | { type: 'task:done'; payload: { task: Task; result: unknown } }
  | { type: 'review:fail'; payload: { task: Task; feedback: string; attempt: number } }
  | { type: 'done'; payload: Summary }
  | { type: 'error'; payload: { message: string } }
